// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSRh6YrLu9b8ybe3C12yRFpEu-h7yvD5A',
    appId: '1:164490231693:web:cab7eb782ad60b799387c4',
    messagingSenderId: '164490231693',
    projectId: 'goldonesia-database',
    authDomain: 'goldonesia-database.firebaseapp.com',
    storageBucket: 'goldonesia-database.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAufSJmZTnm3QpGb0MTXNfOBgMel5OFjKk',
    appId: '1:164490231693:android:9608557e48b3dbd89387c4',
    messagingSenderId: '164490231693',
    projectId: 'goldonesia-database',
    storageBucket: 'goldonesia-database.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNOm1g9hCPbLFUCgozhDc8aErqCWzL2kE',
    appId: '1:164490231693:ios:8317d33f2e9e11899387c4',
    messagingSenderId: '164490231693',
    projectId: 'goldonesia-database',
    storageBucket: 'goldonesia-database.appspot.com',
    iosBundleId: 'com.example.goldonesia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNOm1g9hCPbLFUCgozhDc8aErqCWzL2kE',
    appId: '1:164490231693:ios:be5b2dc099f500bb9387c4',
    messagingSenderId: '164490231693',
    projectId: 'goldonesia-database',
    storageBucket: 'goldonesia-database.appspot.com',
    iosBundleId: 'com.example.goldonesia.RunnerTests',
  );
}
